-- Rebuild Script for Audit-ready Student Management System
-- Generated by Antigravity

-- 1. Create Database
DROP DATABASE IF EXISTS audit_student_db;
CREATE DATABASE audit_student_db;
USE audit_student_db;

-- 2. Create Users Table
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- 3. Create Students Table
CREATE TABLE students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(15),
    department VARCHAR(100),
    year INT,
    address VARCHAR(255),
    cgpa DOUBLE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- 4. Insert Initial Users
-- BCrypt hashed passwords for 'admin123', 'staff123', and 'student123'
INSERT INTO users (username, password, email, role, created_by)
VALUES 
('admin', '$2a$10$8.UnVuG9shgE3.18V8ZzueS879C5J2PUM/c99YVqJUMdE/H3sps3K', 'admin@example.com', 'ADMIN', 'SYSTEM'),
('staff', '$2a$10$X8H.fB3I.E/.M8e9S8.M8e9S8.M8e9S8.M8e9S8.M8e9S8.M8e9S8.', 'staff@example.com', 'STAFF', 'SYSTEM'),
('student_user', '$2a$10$Y9I.gC4J.F/0N9f0T9.N9f0T9.N9f0T9.N9f0T9.N9f0T9.N9f0T9.', 'student@example.com', 'STUDENT', 'SYSTEM');

-- 5. Sample Student Data (Optional)
INSERT INTO students (name, email, phone, department, year, address, cgpa, created_by)
VALUES ('John Doe', 'john.doe@example.com', '1234567890', 'Computer Science', 3, '123 Main St', 8.5, 'SYSTEM');
